services:
  postgres:
    # Use the official PostgreSQL image for Unix-based systems
    image: postgres:16-alpine
    container_name: football_stats_db

    # Environment variables for database creation
    # The image automatically creates this user and database
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase

    ports:
      # Map the host port to the container port to allow external connections
      - "5432:5432"

    volumes:
      # 1. Persistent Data Volume:
      # Mounts a named volume to the postgres data directory.
      # This ensures your data survives container restarts and removals.
      - football_stats_postgres-data:/var/lib/postgresql/data

      # 2. Initialization Script Volume:
      # Mounts your local 'init' folder into the container.
      # The entrypoint script will execute any .sql files in this directory.
      - ./init-db:/docker-entrypoint-initdb.d

    # Restart policy to ensure the container comes back up if it fails
    restart: unless-stopped

# Top-level volumes declaration for Docker to manage
volumes:
  football_stats_postgres-data:
